[2025-01-17 00:11:41,031] 1025 httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-01-17 00:11:41,046] 115 root - ERROR - Error: Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\mcqgen\StreamlitAPP.py", line 109, in <module>
    create_and_print_dataframe(mcqs)
  File "C:\Users\ASUS\Desktop\mcqgen\src\mcqgenerator\utils.py", line 32, in create_and_print_dataframe
    df = pd.DataFrame(quiz_data)
         ^^
NameError: name 'pd' is not defined

